apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: will-app
  namespace: argocd
spec:
  destination:
    namespace: will-app
    server: https://kubernetes.default.svc
  project: will-project
  source:
    path: will-app/
    repoURL: https://github.com/ytaousi/InceptionOfThings/tree/main/p3
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true